---
# tasks file for ansible-role-prosody

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
- name: Include OS specific tasks
  include: "install-{{ ansible_os_family }}.yml"

- name: Configure Prosody
  template:
    src: prosody.cfg.lua
    dest: /etc/prosody/prosody.cfg.lua
    owner: root
    mode: 0755
  notify: restart prosody

- name: Create parameters for Diffie–Hellman (could take a while)
  command: "openssl dhparam -out /etc/prosody/certs/dh-{{ prosody_dhparam_length }}.pem {{ prosody_dhparam_length }}"
  args:
    creates: "/etc/prosody/certs/dh-{{ prosody_dhparam_length }}.pem"
  notify: restart prosody

- name: Get prosody external modules repository
  hg:
    repo: https://hg.prosody.im/prosody-modules/
    revision: default
    update: true
    dest: "{{ prosody_external_modules_path }}"
  tags:
    - skip_ansible_lint

- name: Start and enable prosody on boot
  service:
    name: prosody
    state: started
    enabled: true

- name: Set firewall rules for Prosody
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  with_items:
    - 5222
    - 5269
  when: prosody_setup_ufw
